config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Log in + Sign up + Dashboard btn
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "calendar", to: "pages#calendar"

  get "fake_new", to: "pages#fake_new"

  resources :games, only: :show do
    member do
      get :play
      get :stats
    end
  end

  resources :players do
    member do
      get :player_data
      get :radar_player_data
    end
  end

  resources :coaches, only: %i[new edit update delete] do
    resources :participations, except: %i[index new]
    resources :teams, except: %i[show index]
  end

  resources :player_stats, except: %i[show index] do
    resources :game_stats, only: %i[show new create index]
  end

  resources :games, only: %i[show index] do
    resources :participations, only: %i[new]

    member do
      post 'set_titulaire', to: "participations#titularize"
      get :quarter_data
      get :total_quarter_data
    end
    member do
      post "set_participations", to: "games#set_participations"
    end
  end

  # Add the update_profile route
  put '/update_profile', to: 'pages#update_profile', as: 'update_profile'
end


  # Define a route for displaying the coach's profile and dashboard (Same page)
  # get :profile, to: 'pages#profile', as: :coach_dashboard

  # # Define a route for the coach to prepare for an upcoming game
  # get :prepare_game, to: 'games#prepare_game', as: :prepare_game

  # # Define a route for the coach to select players for an upcoming game
  # post :select_players, to: 'games#select_players', as: :select_players

  # Define a route for displaying the "GAME TIME" message and redirecting to the game play page
  # get :game_in_progress, to: 'games#in_progress', as: :game_in_progress

  # # Define a route for displaying the game play interface
  # get :game_play, to: 'games#play', as: :game_play

app/views/pages/calendar.html.erb
<div class="title-container">
  <h3>Calendar</h3>
</div>

<% @games.each do |game| %>
  <div class="card-game-container-calendar">
      <div class="card-info-calendar">
        <div class="column1">
          <img src="<%= @home_team && @home_team.photo.present? ?cl_image_path(@home_team.photo.key) :asset_path('bcm_logo.png')%>" alt="">
          <p><%= @home_team.city %></p>
        </div>
        <div class="column2">
          <p><%= game.date.strftime("%d-%m-%Y") %></p>
          <p><%= game.arena %></p>
        </div>
        <div class="column3">
          <img src="<%= @away_team && @away_team.photo.present? ?cl_image_path(@away_team.photo.key) :asset_path('sig_logo.png')%>" alt="">
          <p><%= @away_team.city %></p>
        </div>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="title-container">
  <h3>Next Game</h3>
</div>

<div class="card-game-container">
  <% if @next_game %>
    <div class="pregame-card">
      <div class="card-info">
        <img src="<%= @home_team && @home_team.photo.present? ?cl_image_path(@home_team.photo.key) :asset_path('bcm_logo.png')%>" alt="">
        <div class="flex-time">
          <p><%= @next_game.date.strftime("%d-%b-%Y") %></p>
          <p><%= @next_game.arena %></p>
        </div>
        <img src="<%= @away_team && @away_team.photo.present? ?cl_image_path(@away_team.photo.key) :asset_path('sig_logo.png')%>" alt="">
      </div>
      <div class="name-hour">
        <% unless @next_game.nil? %>
          <p><%= @home_team.city %></p>
          <p><%= @away_team.city %></p>
        <% end %>
      </div>
    </div>
    <%= link_to "Prepare your game", new_game_participation_path(@next_game), class: "btn-dashboard"%>
  <% end %>
</div>

<div class="title-container" id="dash">
  <h3 id='Team'>Your Team Stats</h3>
</div>

<div class="card-stats-container">
  <div class="parent">
   <div class="card-infos-orange-img">
      <p><%= @wins %>W - <%= @losses %>L</p>
      <div class="ratio-logo">
        <div class="info-ratio">
         <h4><%= @win_rate %>%</h4>
          <p>Winrate</p>
        </div>
      </div>
    </div>
    <div class="card-infos-white">
      <h4><%= @avg_pts %> pts</h4>
      <p>scored / game</p>
    </div>
    <div class="card-infos-white">
      <h4>1st</h4>
      <p>championship</p>
      <a target ="_blank" href="https://nm1.ffbb.com/classement">go to ranking ></a>
    </div>
    <div class="card-infos-orange-img">
      <div class="MVP-info">
        <p>Last</p>
        <h4>MVP</h4>
      </div>
      <img id='curry' src="<%= @player && @player.photo.present? ?cl_image_path(@player.photo.key) :asset_path('user.png')%>" alt="">
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="global" class="<%= ["img2", "img3", "img4"].sample %>">

  <div id="divlogo">
    <img id="homepagelogo" src="<%= asset_path('gtlogo.png') %>" alt="GameTracks logo">
  </div>
  <div class="flex-home">
    <div id="divgametracks">
      <h1>
        GAME
        <br>
        TRACKS
      </h1>
    </div>
    <div id="divlevelupyourgame">
      <h4><span id="levelup">Level up</span> your game</h4>
    </div>
  </div>

  <div id="divbtn">
    <% if user_signed_in? %>
      <%= link_to "Dashboard", dashboard_path, class: "btn-login btn-center" %>
      <%#= link_to "sign_out", destroy_user_session_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: "btn-login" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn-signup" %>
    <% end %>
  </div>

</div>

app/views/pages/profile.html.erb
<!-- app/views/pages/profile.html.erb -->
<h3>Complete Profile</h3>

<%= form_tag update_profile_path, method: :put do %>

  <%= devise_error_messages! %>

  <div class="form-inputs">
    <div class="form-section">
      <h5>Category</h5>
      <%= select_tag :category, options_for_select(['Coach', 'Player'], selected: @user.category), prompt: 'Select a category' %>
    </div>

    <% if @user.category == "Coach" %>
      <div class="form-section">
        <h5>Club name</h5>
        <%= text_field_tag :club_name, @user.club_name, required: true %>
      </div>

      <div class="form-section">
        <h5>Age level</h5>
        <%= select_tag :age_level, options_for_select(['Senior', 'U20', 'U15'], selected: @user.age_level), prompt: 'Select an age level' %>
      </div>

      <div class="form-section">
        <h5>Category</h5>
        <%= select_tag :coach_category, options_for_select(['N1', 'N2', 'N3', 'R1', 'R2', 'R3', 'D1', 'D2', 'D3'], selected: @user.coach_category), prompt: 'Select a category' %>
      </div>

      <div class="form-section">
        <h5>City</h5>
        <%= text_field_tag :city, @user.city, required: true %>
      </div>
    <% else %>
      <div class="form-section">
        <h5>License ID</h5>
        <%= text_field_tag :license_id, @user.license_id, required: true %>
      </div>

      <div class="form-section">
        <h5>Phone</h5>
        <%= text_field_tag :phone, @user.phone, required: true %>
      </div>

      <div class="form-section">
        <h5>Sex</h5>
        <%= select_tag :sex, options_for_select(['Male', 'Female'], @user.sex), prompt: 'Select a sex' %>
      </div>

      <div class="form-section">
        <h5>Description</h5>
        <%= text_area_tag :description, @user.description, required: true %>
      </div>

      <div class="form-section">
        <h5>Position</h5>
        <%= select_tag :position, options_for_select(['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'], @user.position), prompt: 'Select a position' %>
      </div>

      <div class="form-section">
        <h5>Height</h5>
        <%= text_field_tag :height, @user.height, required: true %>
      </div>
    <% end %>
  </div>

  <div class="form-actions">
    <%= submit_tag "Update Profile", class: "btn btn-primary btn-light" %>
  </div>

<% end %>