config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Log in + Sign up + Dashboard btn
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "calendar", to: "pages#calendar"

  get "fake_new", to: "pages#fake_new"

  resources :games, only: :show do
    member do
      get :play
      get :stats
    end
  end

  resources :players do
    member do
      get :player_data
      get :radar_player_data
    end
  end

  resources :coaches, only: %i[new edit update delete] do
    resources :participations, except: %i[index new]
    resources :teams, except: %i[show index]
  end

  resources :player_stats, except: %i[show index] do
    resources :game_stats, only: %i[show new create index]
  end

  resources :games, only: %i[show index] do
    resources :participations, only: %i[new]

    member do
      post 'set_titulaire', to: "participations#titularize"
      get :quarter_data
      get :total_quarter_data
    end
    member do
      post "set_participations", to: "games#set_participations"
    end
  end

  # Add the update_profile route
  put '/update_profile', to: 'pages#update_profile', as: 'update_profile'
end


  # Define a route for displaying the coach's profile and dashboard (Same page)
  # get :profile, to: 'pages#profile', as: :coach_dashboard

  # # Define a route for the coach to prepare for an upcoming game
  # get :prepare_game, to: 'games#prepare_game', as: :prepare_game

  # # Define a route for the coach to select players for an upcoming game
  # post :select_players, to: 'games#select_players', as: :select_players

  # Define a route for displaying the "GAME TIME" message and redirecting to the game play page
  # get :game_in_progress, to: 'games#in_progress', as: :game_in_progress

  # # Define a route for displaying the game play interface
  # get :game_play, to: 'games#play', as: :game_play

app/models/game.rb
class Game < ApplicationRecord
  # has_one :winner, class_name: :Team, foreign_key: :team_id
  # has_many :game_stats
  has_many :participations
  has_many :teams, -> { distinct }, through: :participations
  has_many :users, -> { distinct }, through: :participations
  has_many :players, through: :participations, source: :user

  validates :date,
            :time,
            :arena,
            :arena_address, presence: true


  def home_team
    teams.joins(:participations).where(participations: { home?: true }).distinct.first
  end

  def my_game_players
    users.joins(:participations).where(participations: { home?: true }).distinct
  end

  def home_team_stats
    ## WARNING
    Participation.where(game: self, team: home_team).map(&:player_stat)
    # Participation.all.map(&:player_stat)
  end

  def compiled_home_stats
    reduced_stats = {
      point: 0,
      rebound: 0,
      assist: 0,
      steal: 0,
      block: 0,
      fg_made: 0,
      fg_attempt: 0,
      threep_made: 0,
      threep_attempt: 0,
      ft_made: 0,
      ft_attempt: 0,
      off_rebound: 0,
      def_rebound: 0,
      turnover: 0,
      fault: 0,
      eval_player: 0
    }

    home_team_stats.compact.each do |stat|
      reduced_stats.keys.each do |key|
        reduced_stats[key] += stat.send(key)
      end
    end

    reduced_stats.merge(eval_mean: reduced_stats[:eval_player] / home_team_stats.count)
  end

  def home_stats_for_chart
    outputs = %i(point assist off_rebound def_rebound turnover)
    home_stats = compiled_home_stats
    stats = {}
    outputs.each do |output|
      stats[output] = home_stats[output]
    end
    stats
  end

  def rebound
    off_rebound + def_rebound
  end

  def away_team
    teams.joins(:participations).where(participations: { home?: false }).distinct.first
  end

  def away_team_stats
    Participation.where(game: self, team: away_team).map(&:player_stat)
  end

  def score_per_quarter_team(game)
    quarters_home = {
      Q1_home: game.Q1_home,
      Q2_home: game.Q2_home,
      Q3_home: game.Q3_home,
      Q4_home: game.Q4_home
    }
  end

  def score_per_quarter_opponent(game)
    quarters_away = {
      Q1_away: game.Q1_away,
      Q2_away: game.Q2_away,
      Q3_away: game.Q3_away,
      Q4_away: game.Q4_away
    }
  end

  def total_score_per_quarter_team(game)
    total_quarters_home = {
      Q1_home: game.Q1_home,
      Q2_home: game.Q1_home + game.Q2_home,
      Q3_home: game.Q1_home + game.Q2_home + game.Q3_home,
      Q4_home: game.Q1_home + game.Q2_home + game.Q3_home + game.Q4_home
    }
  end

  def total_score_per_quarter_opponent(game)
    total_quarters_away = {
      Q1_away: game.Q1_away,
      Q2_away: game.Q1_away + game.Q2_away,
      Q3_away: game.Q1_away + game.Q2_away + game.Q3_away,
      Q4_away: game.Q1_away + game.Q2_away + game.Q3_away + game.Q4_away
    }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:play, :show, :set_participations, :quarter_data, :total_quarter_data]

  def stats
    @game = Game.find(params[:id])
    @home_team_stats = @game.home_team_stats
    home_stats = @game.home_stats_for_chart
    total_team_stats = @game.home_team.total_team_stats_for_chart(@game)
    @game_data = { home_stats: home_stats, total_team_stats: total_team_stats }
    respond_to do |format|
      format.html
      format.json { render json: @game_data }
    end
  end

  def quarter_data
    score_per_quarter_team = @game.score_per_quarter_team(@game)
    score_per_quarter_opponent = @game.score_per_quarter_opponent(@game)

    @quarter_data = { score_per_quarter_team: score_per_quarter_team, score_per_quarter_opponent: score_per_quarter_opponent }

    render json: @quarter_data
  end

  def total_quarter_data
    total_score_per_quarter_team = @game.total_score_per_quarter_team(@game)
    total_score_per_quarter_opponent = @game.total_score_per_quarter_opponent(@game)

    @total_quarter_data = { total_score_per_quarter_team: total_score_per_quarter_team, total_score_per_quarter_opponent: total_score_per_quarter_opponent }

    render json: @total_quarter_data
  end

  def show
    selected = @game.participations.where(selected?: true)
    user_ids = selected.map(&:user_id)
    my_players = User.where(id: user_ids)
    @my_centers = my_players.group_by(&:position)["C"]
    @my_forwards = my_players.group_by(&:position)["F"]
    @my_guards = my_players.group_by(&:position)["G"]
  end

  def index
    @games = current_user.managed_teams.first.games.where("date < :end", end: Date.today).order(date: :desc)
    @home_team = Team.first
    @away_team = Team.second
  end

  def set_participations
    participations = []
    participation_params[:players].each do |user_id|
      team_id = User.find(user_id).teams.first.id
      new_participation = Participation.new(team_id: team_id, user_id: user_id, game_id: @game.id, selected?: true)

      participations << new_participation
    end
    success = participations.all?(&:save)

    if success
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def play
    @skip_navbar = true
    @skip_footer = true
    @participations_selected = @game.participations.where(selected?: true).distinct
    @titulaires = @participations_selected.where(titulaire?: true)
    @non_titulaires = @participations_selected.where(titulaire?: false)
    @away_team = Team.second
    @home_team = Team.first
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def participation_params
    params.permit(:authenticity_token, :commit, :id, players: [])
  end
end

app/views/games/index.html.erb
<div class="title-container">
  <h3>Past games</h3>
</div>

<% @games.each do |game| %>
  <div class="card-game-container-calendar">
    <%= link_to stats_game_path(game), class: "card-info-calendar" do %>
      <div class="column1">
        <img src="<%= @home_team && @home_team.photo.present? ?cl_image_path(@home_team.photo.key) :asset_path('bcm_logo.png')%>" alt="">
        <% if game.winner_id == @home_team.id %>
          <p><strong><%= @home_team.city %></strong></p>
          <p><strong><%= game.score_home_team %></strong></p>
        <% else %>
          <p><%= @home_team.city %></p>
          <p><%= game.score_home_team %></p>
        <% end %>
      </div>
      <div class="column2">
        <p><%= game.date.strftime("%d-%m-%Y") %></p>
      </div>
      <div class="column3">
        <img src="<%= @away_team && @away_team.photo.present? ?cl_image_path(@away_team.photo.key) :asset_path('sig_logo.png')%>" alt="">
        <% if game.winner_id == @away_team.id %>
          <p><strong><%= @away_team.city %></strong></p>
          <p><strong><%= game.score_away_team %></strong></p>
        <% else %>
          <p><%= @away_team.city %></p>
          <p><%= game.score_away_team %></p>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/games/play.html.erb
<div class="megamegadiv" data-controller="add-stats">

  <%= simple_form_for PlayerStat.new do |f| %>
    <%= f.hidden_field :game_id, value: @game.id %>

    <div class="divpoints">

      <div class="divpoints1">

        <%= label_tag :player_stat_ft_made, "1", class: "btn-green-round btn-margin1", data: { type: "ft_made", type_action: '+1 point ☝️', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_2", point: '1' }%>
        <%= check_box_tag "player_stat[ft_made]", "1", false, hidden: true %>

        <%= label_tag :player_stat_fg_made, "2", class: "btn-green-round btn-margin1", data: { type: "fg_made", type_action: '+2 points ✌️', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_2", point: '2' }%>
        <%= check_box_tag "player_stat[fg_made]", "1", false, hidden: true %>

        <%= label_tag :player_stat_threep_made, "3", class: "btn-green-round btn-margin2", data: { type: "threep_made", type_action: '+3 points 👌', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_2", point: '3' }%>
        <%= check_box_tag "player_stat[threep_made]", "1", false, hidden: true %>

        <span class="material-symbols-outlined">menu</span>

      </div>

      <div class="divpoints2">

        <%= label_tag :player_stat_ft_attempt, "1", class: "btn-red-round btn-margin1", data: { type: "ft_attempt", type_action: 'FT missed 💩', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[ft_attempt]", "1", false, hidden: true %>

        <%= label_tag :player_stat_fg_attempt, "2", class: "btn-red-round btn-margin1", data: { type: "fg_attempt", type_action: 'FG missed 💩', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[fg_attempt]", "1", false, hidden: true %>

        <%= label_tag :player_stat_threep_attempt, "3", class: "btn-red-round btn-margin2", data: { type: "threep_attempt", type_action: '3pts missed 💩', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[threep_attempt]", "1", false, hidden: true %>

        <span class="material-symbols-outlined">undo</span>

      </div>

    </div>

    <div class="divaffichage">

      <div class="divdivaff">

        <div class="divaffichage1">
          <img src="<%= asset_path('bcm_logo.png') %>" alt="" class="logomatch">
          <%# SCORE DE LEQUIPE A CHANGER QUAND ON MARQUE %>
          <p data-add-stats-target='myScore'>0</p>
        </div>

        <div class="divaffichage2">
          <img src="<%= asset_path('sig_logo.png') %>" alt="" class="logomatch">
          <%# SCORE DE LEQUIPE A CHANGER QUAND ILS MARQUENT %>
          <p data-add-stats-target='opponentScore'>0</p>
        </div>

      </div>

      <div class="divaffichage3">

        <%# AFFICHER LES 3 DERNIERES STATS PRISES A FAIRE %>
        <div class="alexis">
          <div data-add-stats-target="player"></div>
          <div data-add-stats-target="action"></div>
        </div>

      </div>

    </div>

    <div class="divstats">

      <div class="divstats1">

        <%= label_tag :player_stat_block, "BLK", class: "btn-white-round btn-margin1", data: { type: "block", type_action: 'Block ⛔', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" } %>
        <%= check_box_tag "player_stat[block]", "1", false, hidden: true %>

        <%= label_tag :player_stat_steal, "STL", class: "btn-white-round btn-margin1", data: { type: "steal", type_action: 'Steal 🏀', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[steal]", "1", false, hidden: true %>

        <%= label_tag :player_stat_off_rebound, "OR", class: "btn-white-round btn-margin2", data: { type: "off_rebound", type_action: 'Offensive Rebound 🏀', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[off_rebound]", "1", false, hidden: true %>

        <%# LOGIQUE A BOSSER FORT OU A NE PAS MONTRER PENDANT LA DEMO %>
        <%= label_tag :player_stat_minute, "Sub", class: "btn-rectangle", data: { type: "minute", type_action: 'substitution', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_3" }%>
        <%= check_box_tag "player_stat[minute]", "1", false, hidden: true %>

      </div>

      <div class="divstats2">

        <%= label_tag :player_stat_turnover, "TO", class: "btn-white-round btn-margin1", data: { type: "turnover", type_action: 'Turnover 😩', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[turnover]", "1", false, hidden: true %>

        <%= label_tag :player_stat_assist, "AST", class: "btn-white-round btn-margin1", data: { type: "assist", type_action: 'Assist 🏀', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[assist]", "1", false, hidden: true %>

        <%= label_tag :player_stat_def_rebound, "DR", class: "btn-white-round btn-margin2", data: { type: "def_rebound", type_action: 'Defensive Rebound 🏀', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[def_rebound]", "1", false, hidden: true %>

        <%= label_tag :player_stat_fault, "Foul", class: "btn-rectangle", data: { type: "fault", type_action: 'Foul ❌', action: "click->add-stats#action", bs_toggle: "modal", bs_target: "#stats_1" }%>
        <%= check_box_tag "player_stat[fault]", "1", false, hidden: true %>

      </div>

    </div>

    <%# MODAL POUR LA PRISE DE TOUTES LES STATS %>
    <div class="modal fade" id="stats_1" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="player-modal">
              <% @titulaires.each do |participation| %>
                <div class="card-select-player card-test1 photogood" data-action="click->add-stats#player" data-id="<%= participation.id %>" data-bs-dismiss="modal" data-name="<%= participation.user.name %>">
                  <img src="<%= participation.user.photo.present? ?cl_image_path(participation.user.photo.key) :asset_path('user.png') %>">
                  <p><%= participation.user.player_name %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>


    <%# MODAL POUR LES POINTS MARQUES (5 joueurs titulaires + logo équipe adverse) %>
    <div class="modal fade" id="stats_2" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="player-modal player-team-modal">
              <div class="card-select-player card-test2" data-bs-dismiss="modal"  data-action="click->add-stats#player" data-team='opponent' data-name="<%= @away_team.city %>">
                <img src="<%= asset_path('sig_logo.png') %>" id="logomatchsig">
                <p><%= @away_team.city %></p>
              </div>
              <div class="laura">
                <% @titulaires.each do |participation| %>
                  <div class="card-select-player card-test1 photogood" data-action="click->add-stats#player" data-id="<%= participation.id %>" data-bs-dismiss="modal" data-team='home' data-name="<%= participation.user.name %>">
                    <img src="<%= participation.user.photo.present? ?cl_image_path(participation.user.photo.key) :asset_path('user.png') %>">
                    <p><%= participation.user.player_name %></p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



    <%# MODAL POUR LES CHANGEMENTS %>
    <div class="modal fade" id="stats_3" aria-hidden="true" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="pierre">
              <div class="laura1">
                <% @titulaires.each do |participation| %>
                  <div class="card-select-player card-test1 photogood" data-action='click->add-stats#selectPlayer'>
                    <img src="<%= participation.user.photo.present? ?cl_image_path(participation.user.photo.key) :asset_path('user.png') %>">
                    <p><%= participation.user.player_name %></p>
                    <i class="fa-regular fa-circle-check"></i>
                  </div>
                <% end %>
              </div>
              <div class="laura1">
                <% @non_titulaires.each do |participation| %>
                  <div class="card-select-player card-test2 photogood" data-action='click->add-stats#selectPlayer'>
                    <img src="<%= participation.user.photo.present? ?cl_image_path(participation.user.photo.key) :asset_path('user.png') %>">
                    <p><%= participation.user.player_name %></p>
                    <i class="fa-regular fa-circle-check"></i>
                  </div>
                <% end %>
              </div>
              <div class="laura1">
                <span class="btn-rectangle minibtnnext" data-bs-target="#stats_4" data-bs-toggle="modal">Next</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="stats_4" aria-hidden="true" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="card-test11">
              <span class="timerem">Remaining Time :</span>
              <div class="temps1" style="margin-top: 2vh;">
                <span data-bs-dismiss="modal">10:00</span>
                <span data-bs-dismiss="modal">9:30</span>
                <span data-bs-dismiss="modal">9:00</span>
                <span data-bs-dismiss="modal">8:30</span>
                <span data-bs-dismiss="modal">8:00</span>
              </div>
              <div class="temps1">
                <span data-bs-dismiss="modal">7:30</span>
                <span data-bs-dismiss="modal">7:00</span>
                <span data-bs-dismiss="modal">6:30</span>
                <span data-bs-dismiss="modal">6:00</span>
                <span data-bs-dismiss="modal">5:30</span>
              </div>
              <div class="temps1">
                <span data-bs-dismiss="modal">5:00</span>
                <span data-bs-dismiss="modal">4:30</span>
                <span data-bs-dismiss="modal">4:00</span>
                <span data-bs-dismiss="modal">3:30</span>
                <span data-bs-dismiss="modal">3:00</span>
              </div>
              <div class="temps1">
                <span data-bs-dismiss="modal">2:30</span>
                <span data-bs-dismiss="modal">2:00</span>
                <span data-bs-dismiss="modal">1:30</span>
                <span data-bs-dismiss="modal">1:00</span>
                <span data-bs-dismiss="modal">0:30</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>

</div>


<div class="lillildiv">
  <%= link_to 'End QT1', stats_game_path(Game.find(Game.last.id)), id: 'endQtButton', class: 'btn-rectangle no-underline' %>
</div>


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
  $(document).ready(function() {
    var buttonTexts = ['End QT1', 'End QT2', 'End QT3', 'End Game'];
    var currentButtonTextIndex = 0;

    $('#endQtButton').on('click', function(e) {
      e.preventDefault();

      if (currentButtonTextIndex === buttonTexts.length - 1) {
        window.location.href = '<%= stats_game_path(@game) %>';
        return;
      }

      $(this).text(buttonTexts[++currentButtonTextIndex]);
    });
  });
</script>

app/views/games/show.html.erb
<div class="maximaxidiv" data-controller='checked-player'>

  <div class="title-container" id="titleyourteam">
    <h3>Starters</h3>
    <%= link_to new_game_participation_path(@game) do %>
      <span class="material-symbols-outlined editsymbol">
        edit
      </span>
    <% end %>
  </div>
  <div class="test">
  </div>
  <%= form_with url: set_titulaire_game_path(@game), method: :post, class: "@" do %>
    <div id="terrainbackground" data-checked-player-target='checkboxesContainer'>
      <div class="margin-div">
        <div class="divclass1">
          <% @my_guards.each do |player| %>
            <div class="player-container" data-action='click->checked-player#select'>
              <%= check_box_tag "players[]", player.id, false, id: "player_#{player.id}", class: "checkbox", style: "display: none;" %>
              <%= label_tag "player_#{player.id}", image_tag(player && player.photo.present? ? cl_image_path(player.photo.key) : asset_path('user.png'), alt: "player_picture", class: "imgimgimg") %>
            </div>
          <% end %>
        </div>

        <div class="divclass2">
          <% @my_forwards.each_with_index do |player, index| %>
            <div class="player-container <%= index.even? ? 'divclass21' : 'divclass22' %>" data-action='click->checked-player#select'>
              <%= check_box_tag "players[]", player.id, false, id: "player_#{player.id}", class: "checkbox", style: "display: none;" %>
              <%= label_tag "player_#{player.id}", image_tag(player && player.photo.present? ? cl_image_path(player.photo.key) : asset_path('user.png'), alt: "player_picture", class: "imgimgimg") %>
            </div>
          <% end %>
        </div>

        <div class="divclass3">
          <% @my_centers.each_with_index do |player, index| %>
            <div class="player-container <%= index.even? ? 'divclass31' : 'divclass32' %>" data-action='click->checked-player#select'>
              <%= check_box_tag "players[]", player.id, false, id: "player_#{player.id}", class: "checkbox", style: "display: none;" %>
              <%= label_tag "player_#{player.id}", image_tag(player && player.photo.present? ? cl_image_path(player.photo.key) : asset_path('user.png'), alt: "player_picture", class: "imgimgimg") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="btn-flex" data-checked-player-target='button' hidden>
      <%= submit_tag "Start Game", class: "btn-orange-classic startgame" %>
    </div>
  <% end %>

</div>

app/views/games/stats.html.erb
<div class="title-container">
  <h3>Game Stats</h3>
</div>
<div class="table-wrapper">
  <table class="table table-dark">
    <thead>
      <tr>
        <th class='sticky-col-name' scope="col">NAME</th>
        <th class='row-grey' scope="col">MIN</th>
        <th class='row-grey'scope="col">PTS</th>
        <th class='row-grey'scope="col">REB</th>
        <th class='row-grey'scope="col">AST</th>
        <th class='row-grey'scope="col">STL</th>
        <th class='row-grey'scope="col">BLK</th>
        <th class='row-grey'scope="col">FGM</th>
        <th class='row-grey'scope="col">FGA</th>
        <th class='row-grey'scope="col">%FG</th>
        <th class='row-grey'scope="col">3PM</th>
        <th class='row-grey'scope="col">3PA</th>
        <th class='row-grey'scope="col">3P%</th>
        <th class='row-grey'scope="col">FTM</th>
        <th class='row-grey'scope="col">FTA</th>
        <th class='row-grey'scope="col">%FT</th>
        <th class='row-grey'scope="col">OREB</th>
        <th class='row-grey'scope="col">DREB</th>
        <th class='row-grey'scope="col">TOV</th>
        <th class='row-grey'scope="col">FLT</th>
        <th class='row-grey'scope="col">EVAL</th>
      </tr>
    </thead>
    <tbody>
      <% @home_team_stats.each do |stat| %>
        <tr>
        <% if stat.present? && stat.respond_to?(:player) %>
          <th class='sticky-col' scope="row"><%= stat.player %></th>
            <td><%= stat.minute %></td>
            <td><%= stat.point %></td>
            <td><%= stat.rebound %></td>
            <td><%= stat.assist %></td>
            <td><%= stat.steal %></td>
            <td><%= stat.block %></td>
            <td><%= stat.fg_made %></td>
            <td><%= stat.fg_attempt %></td>
            <td><%= stat.fg_made != 0 ? (stat.fg_made.fdiv(stat.fg_attempt) * 100).round(1) : 0 %></td>
            <td><%= stat.threep_made %></td>
            <td><%= stat.threep_attempt %></td>
            <td><%= stat.threep_made != 0 ? (stat.threep_made.fdiv(stat.threep_attempt) * 100).round(1) : 0 %></td>
            <td><%= stat.ft_made %></td>
            <td><%= stat.ft_attempt %></td>
            <td><%= stat.ft_made != 0 ? (stat.ft_made.fdiv(stat.ft_attempt) * 100).round(1) : 0 %></td>
            <td><%= stat.off_rebound %></td>
            <td><%= stat.def_rebound %></td>
            <td><%= stat.turnover %></td>
            <td><%= stat.fault %></td>
            <td><%= stat.eval_player %></td>

        <% end %>
      </tr>
      <% end %>
        <% game_home_team_stats = @game.compiled_home_stats %>

        <tr>
          <th class='sticky-col' scope ='row'>Total</th>
          <td><%= game_home_team_stats[:minute]%></td>
          <td><%= game_home_team_stats[:point ]%></td>
          <td><%= game_home_team_stats[:rebound]%></td>
          <td><%= game_home_team_stats[:assist]%></td>
          <td><%= game_home_team_stats[:steal]%></td>
          <td><%= game_home_team_stats[:block]%></td>
          <td><%= game_home_team_stats[:fg_made]%></td>
          <td><%= game_home_team_stats[:fg_attempt]%></td>
          <td><%= game_home_team_stats[:fg_attempt] != 0 ? (game_home_team_stats[:fg_made].fdiv(game_home_team_stats[:fg_attempt]) * 100).round(1) : 0 %></td>
          <td><%= game_home_team_stats[:threep_made] %></td>
          <td><%= game_home_team_stats[:threep_attempt] %></td>
          <td><%= game_home_team_stats[:threep_attempt] != 0 ? (game_home_team_stats[:threep_made].fdiv(game_home_team_stats[:threep_attempt]) * 100).round(1) : 0 %></td>
          <td><%= game_home_team_stats[:ft_made] %></td>
          <td><%= game_home_team_stats[:ft_attempt] %></td>
          <td><%= game_home_team_stats[:ft_attempt] != 0 ? (game_home_team_stats[:ft_made].fdiv(game_home_team_stats[:ft_attempt]) * 100).round(1) : 0 %></td>
          <td><%= game_home_team_stats[:off_rebound]%></td>
          <td><%= game_home_team_stats[:def_rebound] %></td>
          <td><%= game_home_team_stats[:turnover] %></td>
          <td><%= game_home_team_stats[:fault] %></td>
          <td><%= game_home_team_stats[:eval_mean] %></td>
        </tr>
    </tbody>
  </table>
</div>

<div class="title-container">
  <h3>Charts Game</h3>
  <div data-chart-target='chart'></div>
</div>

<div class='chart-container' data-controller='chart' data-chart-game-id-value='<%= @game.id %>'>

  <div class="container-bar">
    <h5>Your Team Stats</h5>
    <canvas class='card-chart' id='chart' data-chart-target='chartContainer'></canvas>
  </div>

  <div class="container-line">
    <h5>Points per Quarter</h5>
    <canvas class='card-chart' id='chartLine' data-chart-target='chartLine'></canvas>
  </div>

  <div class="container-line">
    <h5>Points Evolution</h5>
    <canvas class='card-chart' id='chartLineBis' data-chart-target='chartLineBis'></canvas>
  </div>
  
</div>