config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Log in + Sign up + Dashboard btn
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "calendar", to: "pages#calendar"

  get "fake_new", to: "pages#fake_new"

  resources :games, only: :show do
    member do
      get :play
      get :stats
    end
  end

  resources :players do
    member do
      get :player_data
      get :radar_player_data
    end
  end

  resources :coaches, only: %i[new edit update delete] do
    resources :participations, except: %i[index new]
    resources :teams, except: %i[show index]
  end

  resources :player_stats, except: %i[show index] do
    resources :game_stats, only: %i[show new create index]
  end

  resources :games, only: %i[show index] do
    resources :participations, only: %i[new]

    member do
      post 'set_titulaire', to: "participations#titularize"
      get :quarter_data
      get :total_quarter_data
    end
    member do
      post "set_participations", to: "games#set_participations"
    end
  end

  # Add the update_profile route
  put '/update_profile', to: 'pages#update_profile', as: 'update_profile'
end


  # Define a route for displaying the coach's profile and dashboard (Same page)
  # get :profile, to: 'pages#profile', as: :coach_dashboard

  # # Define a route for the coach to prepare for an upcoming game
  # get :prepare_game, to: 'games#prepare_game', as: :prepare_game

  # # Define a route for the coach to select players for an upcoming game
  # post :select_players, to: 'games#select_players', as: :select_players

  # Define a route for displaying the "GAME TIME" message and redirecting to the game play page
  # get :game_in_progress, to: 'games#in_progress', as: :game_in_progress

  # # Define a route for displaying the game play interface
  # get :game_play, to: 'games#play', as: :game_play

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy, :player_data, :radar_player_data]

  def player_data
    player_stat_for_game = @player.player_stat_for_game(@player.games.last)
    avg_player_stats = @player.avg_player_stats(@player)

    @player_data = { player_stat_for_game: player_stat_for_game, avg_player_stats: avg_player_stats}
    render json: @player_data
  end

  def radar_player_data
    radar_total_stats = @player.radar_total_stats(@player)

    @radar_total_stats = { radar_total_stats: radar_total_stats }
    render json: @radar_total_stats
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to players_path, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def index
    @user = current_user
    @team = Team.find_by(coach: @user)
    if @team
      @players = @team.players
    else
      @players = []
    end
  end

  def show
  end

  def edit
  end

  def update
    if @player.update(player_params)
      redirect_to players_path, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_path, notice: 'Player was successfully deleted.'
  end

  private

  def set_player
    @player = User.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :email, :date_of_birth, :category, :photo)
  end
end

app/views/players/index.html.erb
<div class="title-container">
  <h3>Your team:</h3>
</div>
<div class="row col-centered">
  <% @players.each do |player| %>
    <div class="card-list-players col-sm-6">
      <%= link_to player_path(player) do %>
        <img src="<%= player && player.photo.present? ?cl_image_path(player.photo.key) :asset_path('curry.png')%>" alt="player_picture">
        <p><%= player.player_name_full %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/players/show.html.erb
<div class="container">
  <div class="title-container">
    <h3>Players stats</h3>
  </div>
    <div class="columns">
      <div class="column-left">
        <img src="<%= @player && @player.photo.present? ?cl_image_path(@player.photo.key) :asset_path('user.png')%>" alt="player_picture">
        <h4><%= @player.player_name_full %></h4>
        <p><%= @player.teams.first.club_name %></p>

      </div>
      <div class="column-right">
        <div class="content-right">
          <p><%= @player.position %></p>
          <p><%= @player.size_cm %></p>
        </div>
      </div>
    </div>
    <div class="player-description">
      <p><%= @player.description %></p>
    </div>
    <div class="player-display-stats">
      <div class="stat-uniq">
        <p>PPG</p>
        <p class="number-bold"><%= @player.avg_player_stats(@player)[:point] %></p>
      </div>
      <div class="stat-uniq">
        <p>AST</p>
        <p class="number-bold"><%= @player.avg_player_stats(@player)[:assist] %></p>
      </div>
      <div class="stat-uniq">
        <p>REB</p>
        <p class="number-bold"><%= @player.avg_player_stats(@player)[:rebound] %></p>
      </div>
      <div class="stat-uniq">
        <p>EVAL</p>
        <p class="number-bold"><%= @player.avg_player_stats(@player)[:eval_player] %></p>
      </div>
    </div>
    <div class="charts-player">
      <h3>Player Charts</h3>
    </div>

    <div class="chart-container mt-4" data-controller='player-charts'
           data-player-charts-player-id-value='<%= @player.id %>'>

        <div class='container-bar'>
          <h5> Last Game Stats vs Average Game Stats </h5>
          <canvas class='card-chart' id='chart' data-player-charts-target='chartBar'></canvas>
        </div>

        <div class='container-bar'>
          <h5>See Your Strengths </h5>
          <canvas class='card-chart' id='chartRadar' data-player-charts-target='chartRadar'></canvas>
        </div>

    </div>
</div>